[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "axle-ev-control"
version = "0.1.0"
description = "EV Charge Control Panel for Axle Energy"
requires-python = ">=3.9"

[tool.pytest.ini_options]
pythonpath = ["."]